export enum OfferStatusType {
  OFFER_CREATED = 'OFFER_CREATED',
  OFFER_MISSING_INFORMATION = 'OFFER_MISSING_INFORMATION',
  NO_SUPPLIER_FOR_OFFER = 'NO_SUPPLIER_FOR_OFFER',
  FEE_REQUEST_FOR_OFFER = 'FEE_REQUEST_FOR_OFFER',
  WAITING_COMPLETE_FOR_OFFER = 'WAITING_COMPLETE_FOR_OFFER',
  OFFER_COMPLETED = 'OFFER_COMPLETED',
  OFFER_CANCELED = 'OFFER_CANCELED',
}
