export enum MailStatusType {
  CUSTOMER_NEW_OFFER_REQUEST = 'CUSTOMER_NEW_OFFER_REQUEST',
  CUSTOMER_REQUEST_CORRECTION = 'CUSTOMER_REQUEST_CORRECTION',
  CUSTOMER_REQUEST_CORRECTION_REMINDED = 'CUSTOMER_REQUEST_CORRECTION_REMINDED',
  CUSTOMER_REQUEST_CORRECTION_FROM_CUSTOMER = 'CUSTOMER_REQUEST_CORRECTION_FROM_CUSTOMER',
  FEE_REQUEST_FOR_OFFER = 'FEE_REQUEST_FOR_OFFER',
  FEE_REQUEST_FOR_OFFER_REMINDED = 'FEE_REQUEST_FOR_OFFER_REMINDED',
  SUPPLIER_NEW_OFFER = 'SUPPLIER_NEW_OFFER',
  CUSTOMER_OFFER_RESULT = 'CUSTOMER_OFFER_RESULT',
  WAITING_FEE_FOR_OFFER = 'WAITING_FEE_FOR_OFFER',
  INTERNAL_INFORMATION = 'INTERNAL_INFORMATION',
  FILE_NOTIFICATION = 'FILE_NOTIFICATION',

  // Emlak Sektörü İçin Yeni Durumlar
  CUSTOMER_NEW_PROPERTY_REQUEST = 'CUSTOMER_NEW_PROPERTY_REQUEST', // Alıcı yeni emlak talebi gönderdiğinde
  CUSTOMER_NEW_PROPERTY_LISTING = 'CUSTOMER_NEW_PROPERTY_LISTING', // Satıcı yeni emlak ilanı gönderdiğinde (veya sistem algıladığında)
  PROPERTY_VIEWING_REQUEST = 'PROPERTY_VIEWING_REQUEST', // Bir emlak için görüntüleme talebi geldiğinde
  PROPERTY_MATCH_NOTIFICATION = 'PROPERTY_MATCH_NOTIFICATION', // Alıcıya uygun emlak(lar) bulunduğunda bildirim
  AGENT_NEW_LEAD = 'AGENT_NEW_LEAD', // Bir danışmana/emlakçıya yeni bir potansiyel müşteri (alıcı/satıcı) atandığında
  SELLER_PROPERTY_SOLD_NOTIFICATION = 'SELLER_PROPERTY_SOLD_NOTIFICATION', // Satıcının mülkü satıldığında bildirim
  BUYER_REQUEST_FULFILLED_NOTIFICATION = 'BUYER_REQUEST_FULFILLED_NOTIFICATION', // Alıcının talebi karşılandığında (örn. ev bulundu/satın alındı)

  OTHER = 'OTHER',
}
