export enum MatchedPropertyStatus {
  SUGGESTED = 'SUGGESTED',
  VIEWING_REQUESTED = 'VIEWING_REQUESTED',
  INTERESTED = 'INTERESTED',
  NOT_INTERESTED = 'NOT_INTERESTED',
  PENDING = 'PENDING',
  NOTIFIED = 'NOTIFIED',
  VIEWING_SCHEDULED = 'VIEWING_SCHEDULED',
  REJECTED_BY_USER = 'REJECTED_BY_USER',
  ACCEPTED_BY_USER = 'ACCEPTED_BY_USER',
}
