export enum PropertySearchRequestStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  PENDING_USER_INFO = 'PENDING_USER_INFO',
  MATCH_FOUND = 'MATCH_FOUND',
  NO_MATCH_FOUND = 'NO_MATCH_FOUND',
  MATCH_NOTIFICATION_SENT = 'MATCH_NOTIFICATION_SENT',
  USER_RESPONDED = 'USER_RESPONDED',
  CLOSED = 'CLOSED',
}
